// flow-typed signature: d3ce85fdf175d6621bad2e926dac0ad3
// flow-typed version: <<STUB>>/hammerjs_v^2.0.8/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hammerjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'hammerjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hammerjs/changelog' {
  declare module.exports: any;
}

declare module 'hammerjs/hammer' {
  declare module.exports: any;
}

declare module 'hammerjs/hammer.min' {
  declare module.exports: any;
}

declare module 'hammerjs/src/expose' {
  declare module.exports: any;
}

declare module 'hammerjs/src/hammer' {
  declare module.exports: any;
}

declare module 'hammerjs/src/hammer.prefix' {
  declare module.exports: any;
}

declare module 'hammerjs/src/hammer.suffix' {
  declare module.exports: any;
}

declare module 'hammerjs/src/input' {
  declare module.exports: any;
}

declare module 'hammerjs/src/input/mouse' {
  declare module.exports: any;
}

declare module 'hammerjs/src/input/pointerevent' {
  declare module.exports: any;
}

declare module 'hammerjs/src/input/singletouch' {
  declare module.exports: any;
}

declare module 'hammerjs/src/input/touch' {
  declare module.exports: any;
}

declare module 'hammerjs/src/input/touchmouse' {
  declare module.exports: any;
}

declare module 'hammerjs/src/manager' {
  declare module.exports: any;
}

declare module 'hammerjs/src/recognizer' {
  declare module.exports: any;
}

declare module 'hammerjs/src/recognizers/attribute' {
  declare module.exports: any;
}

declare module 'hammerjs/src/recognizers/pan' {
  declare module.exports: any;
}

declare module 'hammerjs/src/recognizers/pinch' {
  declare module.exports: any;
}

declare module 'hammerjs/src/recognizers/press' {
  declare module.exports: any;
}

declare module 'hammerjs/src/recognizers/rotate' {
  declare module.exports: any;
}

declare module 'hammerjs/src/recognizers/swipe' {
  declare module.exports: any;
}

declare module 'hammerjs/src/recognizers/tap' {
  declare module.exports: any;
}

declare module 'hammerjs/src/touchaction' {
  declare module.exports: any;
}

declare module 'hammerjs/src/utils' {
  declare module.exports: any;
}

declare module 'hammerjs/tests/unit/assets/blanket' {
  declare module.exports: any;
}

declare module 'hammerjs/tests/unit/assets/jquery.min' {
  declare module.exports: any;
}

declare module 'hammerjs/tests/unit/assets/lodash.compat' {
  declare module.exports: any;
}

declare module 'hammerjs/tests/unit/assets/qunit' {
  declare module.exports: any;
}

declare module 'hammerjs/tests/unit/assets/utils' {
  declare module.exports: any;
}

declare module 'hammerjs/tests/unit/gestures/test_pan' {
  declare module.exports: any;
}

declare module 'hammerjs/tests/unit/gestures/test_pinch' {
  declare module.exports: any;
}

declare module 'hammerjs/tests/unit/gestures/test_swipe' {
  declare module.exports: any;
}

declare module 'hammerjs/tests/unit/test_enable' {
  declare module.exports: any;
}

declare module 'hammerjs/tests/unit/test_events' {
  declare module.exports: any;
}

declare module 'hammerjs/tests/unit/test_gestures' {
  declare module.exports: any;
}

declare module 'hammerjs/tests/unit/test_hammer' {
  declare module.exports: any;
}

declare module 'hammerjs/tests/unit/test_jquery_plugin' {
  declare module.exports: any;
}

declare module 'hammerjs/tests/unit/test_multiple_taps' {
  declare module.exports: any;
}

declare module 'hammerjs/tests/unit/test_nested_gesture_recognizers' {
  declare module.exports: any;
}

declare module 'hammerjs/tests/unit/test_propagation_bubble' {
  declare module.exports: any;
}

declare module 'hammerjs/tests/unit/test_require_failure' {
  declare module.exports: any;
}

declare module 'hammerjs/tests/unit/test_simultaneous_recognition' {
  declare module.exports: any;
}

declare module 'hammerjs/tests/unit/test_utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hammerjs/changelog.js' {
  declare module.exports: $Exports<'hammerjs/changelog'>;
}
declare module 'hammerjs/hammer.js' {
  declare module.exports: $Exports<'hammerjs/hammer'>;
}
declare module 'hammerjs/hammer.min.js' {
  declare module.exports: $Exports<'hammerjs/hammer.min'>;
}
declare module 'hammerjs/src/expose.js' {
  declare module.exports: $Exports<'hammerjs/src/expose'>;
}
declare module 'hammerjs/src/hammer.js' {
  declare module.exports: $Exports<'hammerjs/src/hammer'>;
}
declare module 'hammerjs/src/hammer.prefix.js' {
  declare module.exports: $Exports<'hammerjs/src/hammer.prefix'>;
}
declare module 'hammerjs/src/hammer.suffix.js' {
  declare module.exports: $Exports<'hammerjs/src/hammer.suffix'>;
}
declare module 'hammerjs/src/input.js' {
  declare module.exports: $Exports<'hammerjs/src/input'>;
}
declare module 'hammerjs/src/input/mouse.js' {
  declare module.exports: $Exports<'hammerjs/src/input/mouse'>;
}
declare module 'hammerjs/src/input/pointerevent.js' {
  declare module.exports: $Exports<'hammerjs/src/input/pointerevent'>;
}
declare module 'hammerjs/src/input/singletouch.js' {
  declare module.exports: $Exports<'hammerjs/src/input/singletouch'>;
}
declare module 'hammerjs/src/input/touch.js' {
  declare module.exports: $Exports<'hammerjs/src/input/touch'>;
}
declare module 'hammerjs/src/input/touchmouse.js' {
  declare module.exports: $Exports<'hammerjs/src/input/touchmouse'>;
}
declare module 'hammerjs/src/manager.js' {
  declare module.exports: $Exports<'hammerjs/src/manager'>;
}
declare module 'hammerjs/src/recognizer.js' {
  declare module.exports: $Exports<'hammerjs/src/recognizer'>;
}
declare module 'hammerjs/src/recognizers/attribute.js' {
  declare module.exports: $Exports<'hammerjs/src/recognizers/attribute'>;
}
declare module 'hammerjs/src/recognizers/pan.js' {
  declare module.exports: $Exports<'hammerjs/src/recognizers/pan'>;
}
declare module 'hammerjs/src/recognizers/pinch.js' {
  declare module.exports: $Exports<'hammerjs/src/recognizers/pinch'>;
}
declare module 'hammerjs/src/recognizers/press.js' {
  declare module.exports: $Exports<'hammerjs/src/recognizers/press'>;
}
declare module 'hammerjs/src/recognizers/rotate.js' {
  declare module.exports: $Exports<'hammerjs/src/recognizers/rotate'>;
}
declare module 'hammerjs/src/recognizers/swipe.js' {
  declare module.exports: $Exports<'hammerjs/src/recognizers/swipe'>;
}
declare module 'hammerjs/src/recognizers/tap.js' {
  declare module.exports: $Exports<'hammerjs/src/recognizers/tap'>;
}
declare module 'hammerjs/src/touchaction.js' {
  declare module.exports: $Exports<'hammerjs/src/touchaction'>;
}
declare module 'hammerjs/src/utils.js' {
  declare module.exports: $Exports<'hammerjs/src/utils'>;
}
declare module 'hammerjs/tests/unit/assets/blanket.js' {
  declare module.exports: $Exports<'hammerjs/tests/unit/assets/blanket'>;
}
declare module 'hammerjs/tests/unit/assets/jquery.min.js' {
  declare module.exports: $Exports<'hammerjs/tests/unit/assets/jquery.min'>;
}
declare module 'hammerjs/tests/unit/assets/lodash.compat.js' {
  declare module.exports: $Exports<'hammerjs/tests/unit/assets/lodash.compat'>;
}
declare module 'hammerjs/tests/unit/assets/qunit.js' {
  declare module.exports: $Exports<'hammerjs/tests/unit/assets/qunit'>;
}
declare module 'hammerjs/tests/unit/assets/utils.js' {
  declare module.exports: $Exports<'hammerjs/tests/unit/assets/utils'>;
}
declare module 'hammerjs/tests/unit/gestures/test_pan.js' {
  declare module.exports: $Exports<'hammerjs/tests/unit/gestures/test_pan'>;
}
declare module 'hammerjs/tests/unit/gestures/test_pinch.js' {
  declare module.exports: $Exports<'hammerjs/tests/unit/gestures/test_pinch'>;
}
declare module 'hammerjs/tests/unit/gestures/test_swipe.js' {
  declare module.exports: $Exports<'hammerjs/tests/unit/gestures/test_swipe'>;
}
declare module 'hammerjs/tests/unit/test_enable.js' {
  declare module.exports: $Exports<'hammerjs/tests/unit/test_enable'>;
}
declare module 'hammerjs/tests/unit/test_events.js' {
  declare module.exports: $Exports<'hammerjs/tests/unit/test_events'>;
}
declare module 'hammerjs/tests/unit/test_gestures.js' {
  declare module.exports: $Exports<'hammerjs/tests/unit/test_gestures'>;
}
declare module 'hammerjs/tests/unit/test_hammer.js' {
  declare module.exports: $Exports<'hammerjs/tests/unit/test_hammer'>;
}
declare module 'hammerjs/tests/unit/test_jquery_plugin.js' {
  declare module.exports: $Exports<'hammerjs/tests/unit/test_jquery_plugin'>;
}
declare module 'hammerjs/tests/unit/test_multiple_taps.js' {
  declare module.exports: $Exports<'hammerjs/tests/unit/test_multiple_taps'>;
}
declare module 'hammerjs/tests/unit/test_nested_gesture_recognizers.js' {
  declare module.exports: $Exports<'hammerjs/tests/unit/test_nested_gesture_recognizers'>;
}
declare module 'hammerjs/tests/unit/test_propagation_bubble.js' {
  declare module.exports: $Exports<'hammerjs/tests/unit/test_propagation_bubble'>;
}
declare module 'hammerjs/tests/unit/test_require_failure.js' {
  declare module.exports: $Exports<'hammerjs/tests/unit/test_require_failure'>;
}
declare module 'hammerjs/tests/unit/test_simultaneous_recognition.js' {
  declare module.exports: $Exports<'hammerjs/tests/unit/test_simultaneous_recognition'>;
}
declare module 'hammerjs/tests/unit/test_utils.js' {
  declare module.exports: $Exports<'hammerjs/tests/unit/test_utils'>;
}
